import * as THREE from "three";
const canvas=document.querySelector('#scene');const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
const scene=new THREE.Scene();scene.background=new THREE.Color('#03131b');scene.fog=new THREE.FogExp2('#0a3140',.035);const camera=new THREE.PerspectiveCamera(35,innerWidth/innerHeight,.1,100);camera.position.set(0,1.6,10);camera.lookAt(0,1,0);
scene.add(new THREE.HemisphereLight(0x9bd9dc,0x071016,1.2));const key=new THREE.SpotLight(0xb8f4f0,800,30,Math.PI/5,.7,1.5);key.position.set(-4,8,5);key.target.position.set(0,1,0);scene.add(key,key.target);const rim=new THREE.PointLight(0x55b9ca,30,12);rim.position.set(4,2,-2);scene.add(rim);
const mermaid=new THREE.Group();scene.add(mermaid);
const skin=new THREE.MeshPhysicalMaterial({color:0xd89b86,roughness:.42,metalness:0,clearcoat:.25,clearcoatRoughness:.18});const tailMat=new THREE.MeshPhysicalMaterial({color:0x147a7d,roughness:.3,metalness:.15,iridescence:.65,iridescenceIOR:1.4,iridescenceThicknessRange:[250,520]});const hairMat=new THREE.MeshPhysicalMaterial({color:0x101b25,roughness:.24,metalness:.05,clearcoat:.5});
const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.64,1.25,16,32),skin);torso.position.y=1.55;torso.scale.set(.7,1,.42);mermaid.add(torso);const neck=new THREE.Mesh(new THREE.CylinderGeometry(.18,.23,.34,24),skin);neck.position.y=2.45;mermaid.add(neck);const head=new THREE.Mesh(new THREE.SphereGeometry(.45,32,24),skin);head.position.set(0,2.82,.02);head.scale.set(.82,1.12,.82);mermaid.add(head);
const hair=new THREE.Mesh(new THREE.SphereGeometry(.53,32,24),hairMat);hair.position.set(0,2.9,-.09);hair.scale.set(1.02,1.15,.9);mermaid.add(hair);for(let i=0;i<9;i++){const lock=new THREE.Mesh(new THREE.CapsuleGeometry(.075,.8,8,12),hairMat);lock.position.set((i-4)*.11,2.48,-.19-Math.abs(i-4)*.015);lock.rotation.z=(i-4)*.1;lock.rotation.x=.25;mermaid.add(lock)}
const eyeMat=new THREE.MeshStandardMaterial({color:0x142f38,roughness:.18,emissive:0x071a1e});for(const x of[-.17,.17]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.055,16,12),eyeMat);eye.position.set(x,2.86,.405);mermaid.add(eye)}
for(const x of[-.36,.36]){const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.13,.9,12,20),skin);arm.position.set(x,1.62,.02);arm.rotation.z=x<0?-0.25:.25;arm.rotation.x=-.45;mermaid.add(arm)}
const tailCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(0,1.05,0),new THREE.Vector3(.08,.1,-.05),new THREE.Vector3(-.2,-1.1,-.15),new THREE.Vector3(.1,-2.05,-.05)]);const tail=new THREE.Mesh(new THREE.TubeGeometry(tailCurve,48,0.42,24,false),tailMat);tail.scale.set(1,1,.75);mermaid.add(tail);const fin=new THREE.Mesh(new THREE.ConeGeometry(.95,.75,32,1,true),tailMat);fin.position.set(.1,-2.45,-.03);fin.rotation.z=Math.PI;fin.scale.set(1,.5,.35);mermaid.add(fin);
const bubbles=new THREE.Group();scene.add(bubbles);for(let i=0;i<90;i++){const m=new THREE.MeshBasicMaterial({color:0x94e8e2,transparent:true,opacity:.18});const b=new THREE.Mesh(new THREE.SphereGeometry(.015+Math.random()*.035,8,8),m);b.position.set((Math.random()-.5)*8,Math.random()*6-2,Math.random()*3-2);b.userData={speed:.15+Math.random()*.25,phase:Math.random()*6};bubbles.add(b)}
const clock=new THREE.Clock();function frame(){const t=clock.getElapsedTime();mermaid.rotation.y=Math.sin(t*.22)*.12;mermaid.position.y=Math.sin(t*.45)*.08;tail.rotation.z=Math.sin(t*1.3)*.045;hair.rotation.y=Math.sin(t*.7)*.035;bubbles.children.forEach(b=>{b.position.y+=b.userData.speed*.008;if(b.position.y>4)b.position.y=-2;b.position.x+=Math.sin(t+b.userData.phase)*.001});renderer.render(scene,camera);requestAnimationFrame(frame)}frame();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
